# -*- mode: ruby -*-
# vi: set ft=ruby :

#RAM
RAM_BIG = 2048;
RAM_SMALL = 512;

# Box images definition
BOX_LINUX = 'ubuntu/trusty64'
BOX_WINDOWS = 'opentable/win-2012r2-standard-amd64-nocm'


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.


  # Shared database machine
  config.vm.define "mysql" do |mysql|
    mysql.vm.box = BOX_LINUX

    mysql.vm.provider "virtualbox" do |vbox|
      vbox.memory = RAM_SMALL
    end

    mysql.vm.hostname = "mysql"
    mysql.vm.network 'private_network', ip: "192.168.50.10", netmask: "255.255.255.0"

    #setup mysql
    mysql.vm.provision :shell, path: "scripts/setup-mysql.sh"

  end

  # Rundeck 1 Machine
  config.vm.define "rundeck1" do |rundeck1|
    rundeck1.vm.box = BOX_WINDOWS

    rundeck1.vm.provider "virtualbox" do |vbox|
      vbox.memory = RAM_BIG
    end

    rundeck1.vm.hostname = "rundeck1"
    rundeck1.vm.network 'private_network', ip: "192.168.50.11", netmask: "255.255.255.0"

    #Installation files.
    rundeck1.vm.synced_folder "files", "/files"
    rundeck1.vm.synced_folder "config", "/config"
    rundeck1.vm.synced_folder "config/rundeck1", "/rundeck_config"
    rundeck1.vm.synced_folder "testdata/rundeck1", "/testresults"
    rundeck1.vm.provision "shell", inline: "copy c:\\files\\rundeckpro-cluster-1.3.8-SNAPSHOT.war c:\\rundeckpro.war"

    #Install & setup software
    rundeck1.vm.provision :shell, path: "scripts/setup-windows-node.bat"

  end


  # Rundeck 2 Machine
  config.vm.define "rundeck2" do |rundeck2|
    rundeck2.vm.box = BOX_WINDOWS

    rundeck2.vm.provider "virtualbox" do |vbox|
      vbox.memory = RAM_BIG
    end

    rundeck2.vm.hostname = "rundeck2"
    rundeck2.vm.network 'private_network', ip: "192.168.50.12", netmask: "255.255.255.0"

    #Installation files.
    rundeck2.vm.synced_folder "files", "/files"
    rundeck2.vm.synced_folder "config", "/config"
    rundeck2.vm.synced_folder "config/rundeck2", "/rundeck_config"
    rundeck2.vm.synced_folder "testdata/rundeck2", "/testresults"
    # rundeck2.vm.provision "shell", inline: "copy c:\\files\\#{ENV['RUNDECK_WAR']} c:\\rundeckpro.war"
    rundeck2.vm.provision "shell", inline: "copy c:\\files\\rundeckpro-cluster-1.3.8-SNAPSHOT.war  c:\\rundeckpro.war"

    #Install & setup software
    rundeck2.vm.provision :shell, path: "scripts/setup-windows-node.bat"

  end

  # Test Node.
  config.vm.define "testnode" do |testnode|
    testnode.vm.box = BOX_LINUX

    testnode.vm.provider "virtualbox" do |vbox|
      vbox.memory = RAM_SMALL
    end

    testnode.vm.hostname = "testnode"
    testnode.vm.network 'private_network', ip: "192.168.50.50", netmask: "255.255.255.0"

    testnode.vm.synced_folder "scripts", "/scripts"
    testnode.vm.synced_folder "files", "/files"
    testnode.vm.synced_folder "config", "/configfiles"

    #setup tests
    testnode.vm.provision :shell, inline: "su vagrant -c /scripts/prepare-tests.sh"

  end

  #Global shared folder
  config.vm.synced_folder "testdata", "/testdata"
  config.vm.synced_folder "testdata/rundeckprologs", "/rundeckprologs"
  config.vm.synced_folder "testdata/resources", "/resources"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
